In [2]:
import numpy as np
arreglo1 = np.array([12,13,14,15,16,17,18,19,20])
arreglo2 = np.flip(arreglo1)
arreglo2

array([20, 19, 18, 17, 16, 15, 14, 13, 12])

In [3]:
fahrenheit = np.array([0,12,45.21,34,99.91,32])
celcius = (fahrenheit-32)/1.8
celcius

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778,   0.        ])

In [4]:
arreglo2 = np.array([0,10,20])
arreglo3 = np.array([20,10,30])

arreglo4 = np.concatenate((arreglo2,arreglo3))
arreglo4

array([ 0, 10, 20, 20, 10, 30])

In [11]:
set1 = set(arreglo4)
lista1 = list(set1)
arreglo5 = np.array(lista1)
arreglo5

array([ 0, 10, 20, 30])